News/News/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news_portal.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('sign_app.urls'))
]

News/news_portal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Author(models.Model):
    rating_autor = models.IntegerField(default=0)

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def update_rating(self):
        sum_rating_post = Post.objects.filter(author=self.id).values('rating_post')
        total_rating_post = sum([i['rating_post'] for i in sum_rating_post])

        sum_rating_comment = Comment.objects.filter(user=self.id).values('rating_comment')
        total_rating_comment = sum([i['rating_comment'] for i in sum_rating_comment])

        sum_rating_comment_post = Comment.objects.filter(post__author__id=self.id).values('rating_comment')
        total_rating_comment_post = sum([i['rating_comment'] for i in sum_rating_comment_post])

        self.rating_autor = total_rating_post * 3 + total_rating_comment + total_rating_comment_post
        self.save()

    def __str__(self):
        return f'{self.user}'


class Category(models.Model):
    name_category = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return f'{self.name_category}'


class Post(models.Model):
    article = 'ar'
    news = 'nw'

    SELECT = [
        (article, 'Статья'),
        (news, 'Новость')
    ]
    type_post = models.CharField(max_length=2, choices=SELECT)
    time_post = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255, default='Заголовок', unique=True)
    text_post = models.TextField(default='текст статьи, новости')
    rating_post = models.IntegerField(default=0)

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    category = models.ManyToManyField('Category', through='PostCategory')

    def like(self):
        self.rating_post += 1
        self.save()

    def dislike(self):
        self.rating_post -= 1
        self.save()

    def preview(self):
        return f'{self.text_post[:124]}...'

    def __str__(self):
        return f'{self.time_post} {self.rating_post}'

    def get_absolute_url(self):
        return reverse('detail', args=[str(self.id)])


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)


class Comment(models.Model):
    text_comment = models.TextField(blank=True)
    time_comment = models.DateTimeField(auto_now_add=True)
    rating_comment = models.IntegerField(default=0)

    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def like(self):
        self.rating_comment += 1
        self.save()

    def dislike(self):
        self.rating_comment -= 1
        self.save()


class Subscribers(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    time_in = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField('Category', through='SubscriberToCategory')

    def __str__(self):
        return f'{self.name} - {self.email}: {self.time_in}'


class SubscriberToCategory(models.Model):
    subscriber = models.ForeignKey('Subscribers', on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)

News/templates/create.html
{% extends 'flatpages/default.html' %}

{% block title %}
Create news
{% endblock title %}

{% block content %}
    <div class="header header_link">
        <ul>
            <li><a href="{% url 'list' %}">На главную</a></li>
        </ul>
    </div>
        {% if request.resolver_match.url_name == 'create_news'%}
            <h1>Создать новость</h1>
        {% elif request.resolver_match.url_name == 'create_article' %}
            <h1>Создать статью</h1>
        {% endif %}
    <div class="create_div">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Создать" class="button_post">
        </form>
    </div>

{% endblock content %}

News/templates/delete.html
{% extends 'flatpages/default.html' %}

{% block title %}
Delete
{% endblock title %}

{% block content %}
    <div class="header header_link">
        <ul>
            <li><a href="{% url 'list' %}">На главную</a></li>
        </ul>
    </div>
    {% if object.type_post == 'nw' %}
        <h1>Удалить новость</h1>
    {% elif object.type_post == 'ar' %}
        <h1>Удалить статью</h1>
    {% endif %}

        <div class="delete_div">
            <form action="" method="post">
                {% csrf_token %}
                <p>Удаляем: <b>"{{ object.title }} ?"</b></p>
                <p>Автор поста: <b>{{ object.author }}</b></p>
                <p>Дата публикации: <b>{{ object.time_post|date:'d F Y' }}</b></p>
                <input type="submit" value="Удалить" class="button_del">
            </form>
        </div>

{% endblock content %}

News/templates/news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}
{% block title %}
Posts
{% endblock title %}

{% block content %}
    <div class="header header_link">
        <ul>
            <li><a href="{% url 'search' %}">Найти пост</a></li>
            <li><a href="{% url 'create_news' %}">Создать новость</a></li>
            <li><a href="{% url 'create_article' %}">Создать статью</a></li>
            <li><a href="{% url 'list' %}">На главную</a></li>
        </ul>
    </div>

    <div class="info_user_div">
        {% if request.user.is_authenticated %}
            <p>Пользователь: <b>{{ request.user.username }}</b></p>
            <p>Email: <b>{{ request.user.email }}</b></p>
            <button class="button_reg"><a href="{% url 'logout' %}">Выйти</a></button>
<!--                кнопка стать автором-->
                {% if is_not_author %}
                    <button class="button_author"><a href="{% url 'upgrade_user' %}">Стать автором</a></button>
                    <p class="author_note"><i>Только <b>автор</b> имеет возможность <br>
                        создавать и редактировать посты!</i></p>
                {% endif %}
<!--                конец кнопки стать автором-->
        {% else %}
            <p><i>Использовать фильтры, редактировать<br> создавать и удалять посты
                могут только<br> зарегистрированные пользователи!</i></p>
            <button class="button_reg"><a href="{% url 'login' %}">Войти</a></button>
        {% endif %}
    </div>

    <h1>Новости и статьи</h1>
    <h3>Количество постов на странице: {{posts|length}}</h3>

    {% if request.user.is_authenticated %}
        {% if subscriber_category %}
            <p class="subscribe_category">
                <small>
                Вы подписаны на категории:
                {% for category in subscriber_category %}
                {{ category.category__name_category }} |
                {% endfor %}
                </small>
            </p>
        {% endif %}
    {% endif %}

    {% if posts %}
        <table class="table list">
            <tr>
                <th>Заголовок</th>
                <th>Ссылка</th>
                <th>Тип поста</th>
                <th>Дата публикации</th>
                <th>Превью</th>
            </tr>
            {% for post in posts %}
            <tr class="list">
                <td>{{ post.title }}</td>
                <td><a href="{% url 'detail' pk=post.pk %}">Читать</a></td>
                <td>{{ post.get_type_post_display }}</td>
                <td>{{ post.time_post|date:'d F Y' }}</td>
                <td>{{ post.text_post|truncatewords:20|filter_words }}</td>
            </tr>
            {% endfor %}
        </table>
        <hr>
    {% else %}
        <h3>Нет новостей!!!</h3>
    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
            {% if page_obj.previous_page_number != 1 %}
                ...
                <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
            {% endif %}
    {% endif %}
    {{ page_obj.number }}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
            {% if paginator.num_pages != page_obj.next_page_number %}
                ...
                <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
            {% endif %}
    {% endif %}
<hr>
{% endblock content %}

News/templates/post.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
    <div class="header header_link">
        <ul>
            <li><a href="{% url 'search' %}">Найти пост</a></li>
            {% if post.type_post == 'nw' %}
                <li><a href="{% url 'create_news' %}">Создать новость</a></li>
                <li><a href="{% url 'update_news' pk=post.pk %}">Редактировать новость</a></li>
                <li><a href="{% url 'delete_news' pk=post.pk %}">Удалить новость</a></li>
            {% elif post.type_post == 'ar' %}
                <li><a href="{% url 'create_article' %}">Создать статью</a></li>
                <li><a href="{% url 'update_article' pk=post.pk %}">Редактировать статью</a></li>
                <li><a href="{% url 'delete_article' pk=post.pk%}">Удалить статью</a></li>
            {% endif %}
            <li><a href="{% url 'list' %}">На главную</a></li>
        </ul>
    </div>

    <div class="info_user_div_detail">
        {% if request.user.is_authenticated %}
            <p>Пользователь: <b>{{ request.user.username }}</b></p>
            <p>Email: <b>{{ request.user.email }}</b></p>
            <button class="button_reg"><a href="{% url 'logout' %}">Выйти</a></button>
<!--                кнопка стать автором-->
                {% if is_not_author %}
                    <button class="button_author"><a href="{% url 'upgrade_user' %}">Стать автором</a></button>
                    <p class="author_note"><i>Только <b>автор</b> имеет возможность <br>
                        создавать и редактировать посты!</i></p>
                {% endif %}
<!--                конец кнопки стать автором-->
        {% else %}
            <p><i>Использовать фильтры, редактировать<br> создавать и удалять посты
                могут только<br> зарегистрированные пользователи!</i></p>
            <button class="button_reg"><a href="{% url 'login' %}">Войти</a></button>
        {% endif %}
    </div>

    <div class="padd">
        <table class="table list">
            <tr>
                <th>Заголовок поста</th>
                <th>Содержание поста</th>
            </tr>
            <tr>
                <td>{{ post.title }}</td>
                <td>{{ post.text_post|filter_words }}</td>
            </tr>
        </table>
        <hr>
        <ul class="list post_ul">
            <li><b>Автор:</b> {{ post.author }}</li>
            <li><b>Дата публикации:</b> {{ post.time_post|date:'d F Y' }}</li>
            <li><b>Время публикации:</b> {{ post.time_post|time:'H:i:s' }}</li>
        </ul>

        {% if user.is_authenticated %}
            <ul class="list post_ul">
                <li>Подписаться на данную категорию постов </li>
                {% for cat in post.category.all %}
                    <!-- начало блока кода (отображение кнопки subscribe если не подписан) -->
                    <li class="list_category">
                        {{ cat }}

                        {% if cat.id not in subscriber_category or is_not_subscriber %}
                            <button class="subscribe_button"><a href="{% url 'detail' pk=post.pk %}subscribe/{{ cat.pk }}">Subscribe</a></button>
                        {% else %}
                            <button class="subscribe_button"><a href="{% url 'detail' pk=post.pk %}delete_subscribe/{{ cat.pk }}">Unsubscribe</a></button>
                            <i class="subscribe_text"><small> Вы подписаны! </small></i>
                        {% endif %}

                    </li>
                    <!-- конец блока кода (отображение кнопки subscribe если не подписан) -->
                {% endfor %}
            </ul>
        {% endif %}
    </div>
{% endblock content %}

News/templates/search.html
{% extends 'flatpages/default.html' %}

{% block title %}
Search
{% endblock title %}

{% block content %}
    <div class="header header_link">
        <ul>
            <li><a href="{% url 'list' %}">На главную</a></li>
        </ul>
    </div>
    <h1>Найти пост</h1>
    <div class="search_div">
        <form action="{% url 'list' %}" method="get">
            {{ filterset.form.as_p }}
            <input type="submit" value="Искать" class="button_post">
        </form>
    </div>

{% endblock content %}

News/templates/send_message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            background: linear-gradient( to right, #48D1CC, #40E0D0, #AFEEEE );
        }
    </style>
    <title>Title</title>
</head>
<body>
    <h2>Здравствуйте, {{ username }}! Новая статья в твоем любимом разделе!</h2>
    <p><b>Заголовок поста:</b> {{ title }}</p>
    <p><b>Краткое содержание:</b> {{ text_post }}</p>
    <h3><a href="{{ link }}">Читать в источнике</a></h3>
</body>
</html>

News/templates/send_message_by_celery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            background: linear-gradient( to right, #48D1CC, #40E0D0, #AFEEEE );
        }
    </style>
    <title>Title</title>
</head>
<body>
    <h2>Здравствуйте, {{ username }}! Новая статья в твоем любимом разделе!</h2>
    <p><b>Заголовок поста:</b> {{ title }}</p>
    <p><b>Краткое содержание:</b> {{ text_post }}</p>
    <h3><a href="{{ link }}">Читать в источнике</a></h3>
    <p>письмо отправлено при помощи Celery</p>
</body>
</html>

News/templates/send_posts_week.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body {
            background: linear-gradient( to right, #48D1CC, #40E0D0, #AFEEEE );
        }
        div {
        with: 90%;
        border: solid 1px gray;
        border-radius: 10px;
        padding-left: 20px;
        margin 0 auto;
        }
    </style>
    <title>Title</title>
</head>
<body>
    <div>
        <h2>Здравствуйте, {{ username }}! Подборка постов за неделю по вашей подписке!</h2>
        {% for post in posts %}
            <p><b>Заголовок:</b> {{ post.title }}</p>
            <p><b>Краткое содержание:</b>{{ post.text_post|truncatechars:50 }}</p>
            <h3><a href="{{ link }}{{ post.id }}">Читать в источнике</a></h3>
            <hr>
        {% endfor %}
    </div>
</body>
</html>

News/templates/send_posts_week_by_celery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        div {
            background: linear-gradient( to right, #48D1CC, #40E0D0, #AFEEEE );
            with: 90%;
            border: solid 1px gray;
            border-radius: 10px;
            padding-left: 20px;
            margin 0 auto;
        }
    </style>
    <title>Title</title>
</head>
<body>
    <div>
        <h2>Здравствуйте, {{ username }}! Подборка постов за неделю по вашей подписке!</h2>
        {% for post in posts %}
            <p><b>Заголовок:</b> {{ post.title }}</p>
            <p><b>Краткое содержание:</b>{{ post.text_post|truncatechars:50 }}</p>
            <h3><a href="{{ link }}{{ post.id }}">Читать в источнике</a></h3>
            <hr>
        {% endfor %}
    </div>
<p>Рассылка писем при помощи Celery</p>
</body>
</html>

News/templates/update.html
{% extends 'flatpages/default.html' %}

{% block title %}
Update news
{% endblock title %}

{% block content %}
    <div class="header header_link">
        <ul>
            <li><a href="{% url 'list' %}">На главную</a></li>
        </ul>
    </div>
    <h1>Редактировать новость</h1>
    <div class="create_div">
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Сохранить" class="button_post">
        </form>
    </div>

{% endblock content %}